<a href="https://colab.research.google.com/github/DivyaMeenaSundaram/NLP/blob/main/Sentiment_Classification_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.datasets import imdb

In [5]:
import pandas as pd

df = pd.read_csv("IMDB Dataset.csv")

df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
df.shape

(4999, 2)

In [7]:
df['sentiment'].value_counts()

sentiment
negative    2531
positive    2468
Name: count, dtype: int64

In [8]:
df.sample(5)

                                                 review sentiment
3633  The only reason that this movie is rated a 1 i...  negative
4805  I happened into the den this morning during th...  positive
2170  i was looking forward to this, and to be hones...  negative
1421  If Alien, Jurassic Park and countless other sc...  negative
4543  I've never saw the first three, but I know the...  negative

In [9]:
X = df['review']

y = df['sentiment']

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')

In [12]:
X_train_tfidf = vectorizer.fit_transform(X_train)

In [13]:
X_test_tfidf = vectorizer.transform(X_test)

In [14]:
print(X_train_tfidf.shape)

(3999, 34700)

In [15]:
print(vectorizer.get_feature_names_out()[:20])

['00' '000' '007' '00am' '01' '01pm' '02' '04' '05' '06' '07' '08' '09'
 '10' '100' '1000' '100s' '100th' '101' '102']

In [16]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [17]:
y_pred = model.predict(X_test_tfidf)

In [18]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.864

In [19]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

    negative       0.87      0.87      0.87       526
    positive       0.86      0.86      0.86       474

    accuracy                           0.86      1000
   macro avg       0.86      0.86      0.86      1000
weighted avg       0.86      0.86      0.86      1000

In [20]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[457  69]
 [ 67 407]]

In [21]:
review = [
    "The movie was absolutely fantastic. I loved every scene."
]

review_tfidf = vectorizer.transform(review)

prediction = model.predict(review_tfidf)

print(prediction)

['positive']

In [22]:
review = [
    "This was the worst movie I have ever watched."
]

review_tfidf = vectorizer.transform(review)

prediction = model.predict(review_tfidf)

print(prediction)

['negative']